package Interfaz;
/**
 * @author Alejandro Erazo
 */

public class Ini extends javax.swing.JFrame {

    //-- Conexion --//
    

    // ----------------------------------
    // Constructor
    // ----------------------------------
    public Ini() {
        
        initComponents();
        
        //-- Codigo para mostrar la tabla en el centro de la pantalla --//
        this.setLocationRelativeTo(null);
        
        Registro a = new Registro();
    }
    
    // ----------------------------------
    // Metodos
    // ----------------------------------
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 0, 65)); // NOI18N
        jLabel2.setText("Motos BMW");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel3.setText("Esta aplicacion esta diseñada para brindarle el mejor servicio a nustros clientes, dando la posibilidad de realizar la compra de una moto BMW");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel4.setText("de alta gama teniendo la posibilidad de añadir las caracteristicas de su preferencia.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        jLabel5.setText("Sport");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1. HP4 RACE.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel7.setText("HP4 Race");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jButton2.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton2.setText("Mas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1. Nueva R1250RS.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel9.setText("Nueva S 1000 RR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jButton3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton3.setText("Mas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        jLabel10.setText("Roadster");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2. S1000R.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2. F800R.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel13.setText("S 1000 R");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel14.setText("F 800 R");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, -1, -1));

        jButton4.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton4.setText("Mas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        jButton5.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton5.setText("Mas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        jLabel15.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        jLabel15.setText("Heritage");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3. RNineT.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 420, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel17.setText("R Nine T");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3. RNineT Pure.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jLabel19.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel19.setText("R Nine T Pure");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, -1, -1));

        jButton6.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton6.setText("Mas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        jButton7.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton7.setText("Mas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel20.setText("Usuario:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 650, -1, -1));

        jLabel22.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel22.setText("Nombre:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, -1, -1));

        jLabel23.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        MotosInfo a = new MotosInfo ( );
        a.ocultarInfo();
        a.mostrarInfoHP4RACE();
        
        String nom = "HP4 Race";
        String cc = "Cilindrada: 999 cc";
        String kw = "KW: 215 CV a 13.000 rpm";
        String precio = "152000000";
        String categoria = "Sport";
        
        a.jLabel3.setText(nom);
        a.jLabel63.setText(cc);
        a.jLabel13.setText(kw);
        a.jLabel14.setText(precio);
        a.jLabel10.setText(categoria);
        
        String nombre = jLabel23.getText();
        String user = jLabel21.getText();
        a.jLabel16.setText(nombre);
        a.jLabel17.setText(user);
        
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        MotosInfo a = new MotosInfo ( );
        a.ocultarInfo();
        a.mostrarInfoNuevaS1000RR();
        
        String nom = "Nueva S 1000 RR";
        String cc = "Cilindrada: 1010 cc";
        String kw = "KW: 152 CV a 13.500";
        String precio = "76870000";
        String categoria = "Sport";
        
        a.jLabel3.setText(nom);
        a.jLabel63.setText(cc);
        a.jLabel13.setText(kw);
        a.jLabel14.setText(precio);
        a.jLabel10.setText(categoria);
        
        String nombre = jLabel23.getText();
        String user = jLabel21.getText();
        a.jLabel16.setText(nombre);
        a.jLabel17.setText(user);
        
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        MotosInfo a = new MotosInfo ( );
        a.ocultarInfo();
        a.mostrarInfoS1000R();
        
        String nom = "S 1000 RR";
        String cc = "Cilindrada: 999 cc";
        String kw = "KW: 165 CV a 11.000 rpm";
        String precio = "49000000";
        String categoria = "Roadster";
        
        a.jLabel3.setText(nom);
        a.jLabel63.setText(cc);
        a.jLabel13.setText(kw);
        a.jLabel14.setText(precio);
        a.jLabel10.setText(categoria);
        
        String nombre = jLabel23.getText();
        String user = jLabel21.getText();
        a.jLabel16.setText(nombre);
        a.jLabel17.setText(user);
        
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        MotosInfo a = new MotosInfo ( );
        a.ocultarInfo();
        a.mostrarInfoF800R();
        
        String nom = "F 800 R";
        String cc = "Cilindrada: 798 cc";
        String kw = "KW: 135 CV a 13.000 rpm";
        String precio = "34000000";
        String categoria = "Roadster";
        
        a.jLabel3.setText(nom);
        a.jLabel63.setText(cc);
        a.jLabel13.setText(kw);
        a.jLabel14.setText(precio);
        a.jLabel10.setText(categoria);
        
        String nombre = jLabel23.getText();
        String user = jLabel21.getText();
        a.jLabel16.setText(nombre);
        a.jLabel17.setText(user);
        
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        MotosInfo a = new MotosInfo ( );
        a.ocultarInfo();
        a.mostrarInfoRNineT();
        
        String nom = "R Nine T";
        String cc = "Cilindrada: 1170 cc";
        String kw = "KW: 105 CV a 10.000 rpm";
        String precio = "54000000";
        String categoria = "Heritage";
        
        a.jLabel3.setText(nom);
        a.jLabel63.setText(cc);
        a.jLabel13.setText(kw);
        a.jLabel14.setText(precio);
        a.jLabel10.setText(categoria);
        
        String nombre = jLabel23.getText();
        String user = jLabel21.getText();
        a.jLabel16.setText(nombre);
        a.jLabel17.setText(user);
        
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        MotosInfo a = new MotosInfo ( );
        a.ocultarInfo();
        a.mostrarInfoRNineTPure();
        
        String nom = "R Nine T Pure";
        String cc = "Cilindrada: 1170 cc";
        String kw = "KW: 110 CV a 10.000 rpm";
        String precio = "41000000";
        String categoria = "Heritage";
        
        a.jLabel3.setText(nom);
        a.jLabel63.setText(cc);
        a.jLabel13.setText(kw);
        a.jLabel14.setText(precio);
        a.jLabel10.setText(categoria);
        
        String nombre = jLabel23.getText();
        String user = jLabel21.getText();
        a.jLabel16.setText(nombre);
        a.jLabel17.setText(user);
        
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        IniciarSesion a = new IniciarSesion();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
